CREATE TABLE USER(
ID IDENTITY PRIMARY KEY,
NAME VARCHAR(100), 
LOGIN VARCHAR(100), 
PASSWORD VARCHAR(100));

CREATE TABLE TALK(
ID IDENTITY PRIMARY KEY,
DATE TIMESTAMP,
TYPETALK CHAR(1),
ACTIVE BOOLEAN);

CREATE TABLE MESSAGE(
ID IDENTITY PRIMARY KEY,
ID_USER BIGINT(19),
ID_TALK BIGINT(19),
DATE TIMESTAMP,
TEXT VARCHAR(500));

ALTER TABLE MESSAGE ADD CONSTRAINT FK_ID_USER FOREIGN KEY(ID_USER) REFERENCES USER(ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MESSAGE ADD CONSTRAINT FK_ID_TALK FOREIGN KEY(ID_TALK) REFERENCES TALK(ID) ON DELETE CASCADE ON UPDATE CASCADE;
